# Generated by Django 3.1.1 on 2020-09-12 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miromi_first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautydata',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beautydata',
            name='hair_colour',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beautydata',
            name='user_person',
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
