# Generated by Django 3.1.1 on 2020-09-12 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miromi_first', '0002_auto_20200912_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beautydata',
            name='user_person',
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
