# Generated by Django 3.1.1 on 2020-09-12 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miromi_first', '0004_auto_20200912_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beautydata',
            name='user_person',
        ),
        migrations.AddField(
            model_name='beautydata',
            name='new_user',
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
